spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://192.168.31.100:3306/test?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: MyDifficultPass4@
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  #配置mail信息
  mail:
    host: smtp.163.com
    username: kamisora2020@163.com
    password: VBWQMVCCRAHOFNDE
    port: 465
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

  #配置redis
  redis:
    host: 192.168.234.101
mybatis-plus:
  global-config:
    db-config:
      # id生成策略 auto为数据库自增
      id-type: auto
    #关闭驼峰映射  当然了不推荐关闭
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
