spring:
  jpa:
    #开启SQL语句执行日志信息
    show-sql: true #打印sql语句
    hibernate:
      #配置为自动创建
      ddl-auto: update
  #配置数据源
  datasource:
    url: jdbc:mysql://192.168.31.100:3306/test
    username: root
    password: MyDifficultPass4@
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  #  #配置mail信息
  mail:
    host: smtp.163.com
    username: kamisola2020@163.com
    password: VBWQMVCCRAHOFNDE
    port: 465
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

  #配置redis
  redis:
    host: 192.168.234.101
